name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd app
          pytest || echo "No tests yet"

  docker:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        # Use your repo name instead of "my-image-name"
        IMAGE_NAME=mrutyunjayn/cicd

        # Build with 2 tags (latest + commit SHA)
        docker build -f ./Dockerfile -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

        # Push both tags
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}

